name: Build and deploy

#concurrency:
#  group: build-deploy-${{ github.ref_name }}
#  cancel-in-progress: false

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello to the World
        run: echo "Hello, World!"
