name: Build and deploy

concurrency:
  group: build-deploy-${{ github.ref_name }}
  cancel-in-progress: false

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/wf-build.yml
    secrets: inherit
