name: Build and deploy

concurrency:
  group: build-deploy-${{ github.ref_name }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_call:

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/wf-build.yml
    secrets: inherit
