name: Build and deploy

concurrency:
  group: build-deploy-${{ github.ref_name }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  ci:
    uses: ./.github/workflows/wf-build.yml
    secrets: inherit
