name: Publish

concurrency:
  group: build-deploy-${{ github.ref_name }}
  cancel-in-progress: false

on:
  workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/wf-ci.yml
    secrets: inherit

  publish:
    uses: ./.github/workflows/wf-cd.yml
    secrets: inherit
