name: Publish

concurrency:
  group: build-deploy-${{ github.ref_name }}
  cancel-in-progress: false

on:
  workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/wf-ci.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: ci
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git User
        run: |
          git config user.email "getpaulj@gmail.com"
          git config user.name "getpaulj - ci pipeline"

      - name: Lerna Version
        run: npm run all:version

      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          scope: '@chrysalis-it'

      - name: Show Changed
        if: ${{ github.ref_name == 'main' }}
        id: show_changed
        run: |
          COMMITS=$(git rev-list --reverse origin/main..HEAD | wc -l)
          if [ $COMMITS > 0 ]; then
            echo "Changes Detected"
            echo "has_changes=Yes" >> $GITHUB_OUTPUT
          else
            echo "No Change Detected"
            echo "has_changes=No" >> $GITHUB_OUTPUT
          fi

      - name: Build
        if: ${{ github.ref_name == 'main' && success() && steps.show_changed.outputs.has_changes == 'Yes' }}
        run: |
          set -e
          git status
          npm i
          npm run all:compile

      - name: Setup Publish NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@chrysalis-it'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

      - name: Publish
        if: ${{ github.ref_name == 'main' && success() && steps.show_changed.outputs.has_changes == 'Yes' }}
        run: |
          set -e
          git status
          npm run all:publish
          git push --follow-tags --no-verify
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
