name: ~Build

on:
  pull_request:
  workflow_call:

permissions:
  contents: read
#  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM install
        run: |
          npm ci
          npm run all:compile

  test-micro:
    runs-on: ubuntu-latest
    name: Micro Test
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM install
        run: |
          npm ci

      - name: Micro Test
        run: |
          npm run test:micro

  test-integration:
    runs-on: ubuntu-latest
    name: Integration Test
    needs: test-micro
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM install
        run: |
          npm ci

      - name: Integration Test
        run: |
          npm run docker:up
          npm run all:compile
          npm run docker:localstack:wait
          npm run docker -- exec -T dev npm run test:integration
          npm run docker:down

#  deploy:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - uses: actions/checkout@v4
#      # Setup .npmrc file to publish to GitHub Packages
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '20.x'
#          registry-url: 'https://npm.pkg.github.com'
#          # Defaults to the user or organization that owns the workflow file
#          scope: '@chrysalis'
#      - run: npm ci
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}