permissions:
  contents: read

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: lint
#        run: npm run lint
      - name: build
        run: |
          npm ci
          npm run all:compile

  test-micro:
    runs-on: ubuntu-latest
    name: Micro Test
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          npm ci
          npm run all:compile
      - name: Micro Test
        run: npm run test:micro

  test-integration:
    runs-on: ubuntu-latest
    name: Integration Test
    needs: test-micro
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          npm ci
          npm run all:compile
      - name: Integration Test
        run: |
          npm run docker:up
          npm run docker:localstack:wait
          npm run docker -- exec -T dev npm run test:integration
          npm run docker:down

